[build]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh"
  publish = "_site"
  environment = { PHP_VERSION = "7.2", CECIL_VERSION = "5.14.4" }

[context.deploy-preview]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh $DEPLOY_PRIME_URL"

[template.environment]
  CECIL_TITLE = "Title"
  CECIL_DESCRIPTION = "Description"
