backend:
  name: git-gateway
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
logo_url: https://the-butler.cecil.app/admin/cecil-logo-netlify.png
show_preview_links: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - label: "Posts"
    name: "posts"
    label_singular: "Post"
    description: >
      Blog posts.
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: true}
    sortable_fields: ['title', 'date']
    view_filters:
      - label: Draft
        field: draft
        pattern: true
  - label: "Pages"
    name: "pages"
    label_singular: "Page"
    description: >
      Single pages.
    delete: false
    preview_path: "{{title}}"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "About"}
          - {label: "Text", name: "body", widget: "markdown"}
          - {label: "Menu", name: "menu", widget: "string", default: "main"}
          - {label: "Draft", name: "draft", widget: "boolean", default: true, required: true}
  - label: "Settings"
    name: "settings"
    description: >
      Site settings.
    delete: false
    editor:
      preview: false
    files:
      - label: "Configuration"
        name: "config"
        file: "config.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Cecil", required: true}
          - {label: "Baseline", name: "baseline", widget: "string", default: "Your blog's butler.", required: true}
          - {label: "Description", name: "description", widget: "string", default: "A ready to use static blog, powered by Cecil and Hyde.", required: true}
          - {label: "Base URL", name: "baseurl", widget: "string", default: "/", required: true}
          - {label: "Use canonical URL", name: "canonicalurl", widget: "boolean", default: true, required: true}
          - {label: "Theme", name: "theme", widget: "string", default: "hyde"}
          - label: "Date"
            name: "date"
            widget: "object"
            fields:
              - {label: "Format", name: "format", widget: "string", default: "j F Y", required: true}
              - {label: "Time zone", name: "timezone", widget: "string", default: "Europe/Paris", required: true}
          - label: "Virtual pages"
            name: "virtualpages"
            widget: "list"
            fields:
              - {label: "Path", name: "path", widget: "string", required: true}
              - {label: "Layout", name: "layout", widget: "string", required: false}
              - {label: "Output", name: "output", widget: "string", required: false}
              - {label: "Title", name: "title", widget: "string", required: false}
          - label: "Output"
            name: "output"
            widget: "object"
            fields:
              - label: "Formats"
                name: "formats"
                widget: "list"
                fields:
                  - {label: "mediatype", name: "mediatype", widget: "string", hint: "ex: text/plain", required: true}
                  - {label: "extension", name: "extension", widget: "string", required: false}
          - label: "Netlify"
            name: "netlify"
            widget: "object"
            fields:
              - label: "CMS"
                name: "cms"
                widget: "object"
                fields:
                  - {label: "Path", name: "path", widget: "string", default: "admin", required: true}
                  - {label: "Version", name: "version", widget: "string", default: "latest", required: true}
              - label: "Identity"
                name: "identity"
                widget: "object"
                fields:
                  - {label: "Version", name: "version", widget: "string", default: "v1", required: true}
