---
new_page_extension: md
auto_deploy: true
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - page
- type: document
  path: config.yml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - PHP_VERSION=7.2
  - CECIL_VERSION=4.19.2
  preview_output_directory: _site
  install_dependencies_command: bash .forestry/install.sh
  preview_docker_image: composer:latest
  mount_path: "/usr/src"
  working_dir: "/usr/src"
  instant_preview_command: php cecil.phar serve -d --host=0.0.0.0 --port=8080
  publish_command: curl -SOL https://cecil.app/cecil.phar && php cecil.phar build -v
  publish_env:
  - PHP_VERSION=7.2
  - CECIL_VERSION=4.19.2
  output_directory: _site
  preview_command: curl -SOL https://cecil.app/cecil.phar && php cecil.phar build -v --baseurl=$DEPLOY_URL
