---
new_page_extension: md
auto_deploy: true
admin_path: "/static/forestry"
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - page
- type: document
  path: config.yml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - PHP_VERSION=7.2
  - CECIL_VERSION=5.42.5
  preview_output_directory: _site
  install_dependencies_command: bash ./scripts/forestry-install.sh
  preview_docker_image: phpdocker/phpdocker:7.2
  mount_path: "/usr/src"
  working_dir: "/usr/src"
  instant_preview_command: php cecil.phar serve --host=0.0.0.0 --port=8080 -v -d --postprocess=no
